name: Build Application

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build.yaml

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: ./.github/actions/build.yaml

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: ./.github/actions/build.yaml
