name: Gradle QT Application Example

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-project:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true

      - id: platform
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.RUNNER_OS }}

      - name: Run build with Gradle Wrapper
        env:
          JAVA_HOME: JAVA_HOME_17_X64
        run: ./gradlew build

      - name: Test application
        uses: coactions/setup-xvfb@v1
        with:
          run: ${{ github.workspace }}/build/exe/main/debug/${{ steps.platform.outputs.lowercase }}/qt-application-example --version
