name: Gradle QT Application Example

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-project:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Test application on Linux
        if: ${{ matrix.os }} == "ubuntu-latest"
        uses: coactions/setup-xvfb@v1
        with:
          run: ${{ github.workspace }}/build/exe/main/debug/linux/qt-application-example --version
      - name: Test application on MacOS
        if: ${{ matrix.os }} == "macos-latest"
        run: ${{ github.workspace }}/build/exe/main/debug/macos/qt-application-example --version
